#!/bin/bash
# 🟢 Open __LABEL__ Course — double-click in Finder to study. Works on any Mac: needs only bash, curl,
# open and uname, which every Mac has; the app itself is the single executable in .player/bin.
#
# Generated by scripts/deploy.sh from launcher/open-course.command in the course-player repo.
# Edit the template there, not this copy (the next deploy overwrites it).

cd "$(dirname "$0")" || exit 1

PORT=8795
URL="http://localhost:$PORT"

# Already running (another Terminal window, or a browser tab was just closed)? Just show it.
if curl -fsS -m 1 "$URL/api/ping" 2>/dev/null | grep -q '"app":"course-player"'; then
  open "$URL"
  exit 0
fi

case "$(uname -m)" in
  arm64) BIN=".player/bin/course-player-arm64" ;;
  *) BIN=".player/bin/course-player-x64" ;;
esac
if [ ! -f "$BIN" ]; then
  echo "Can't find $BIN — the course folder looks incomplete. Re-run the deploy."
  exit 1
fi

echo "__LABEL__ course is running at $URL — press Quit in the app or close this window to stop."
echo
"$BIN" --root "$PWD" --port "$PORT" --open
echo
echo "Stopped. You can close this window."
